spring:
  application:
    name: hi-doc-api-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres.tailce422e.ts.net:5432/hidoc}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

ai:
  providers:
    openai:
      api-key: ${OPENAI_API_KEY:changeme}
      model: ${OPENAI_MODEL:gpt-4o-mini}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    grok:
      api-key: ${GROK_API_KEY:dummy}
      model: ${GROK_MODEL:grok-2-mini}
      base-url: ${GROK_BASE_URL:https://api.x.ai/v1}
    gemini:
      api-key: ${GEMINI_API_KEY:dummy}
      model: ${GEMINI_MODEL:gemini-1.5-flash}
      base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1}

rate-limiting:
  monthly-limit: 100

cache:
  enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ttl-seconds: 300
