spring:
  application:
    name: hi-doc-api-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres.tailce422e.ts.net:5432/HiDoc}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false

ai:
  providers:
    openai:
      enabled: ${OPENAI_ENABLED:true}
      model: ${OPENAI_MODEL:gpt-4o-mini}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    grok:
      enabled: ${GROK_ENABLED:false}
      api-key: ${GROK_API_KEY:dummy}
      model: ${GROK_MODEL:grok-2-mini}
      base-url: ${GROK_BASE_URL:https://api.x.ai/v1}
    gemini:
      enabled: ${GEMINI_ENABLED:false}
      api-key: ${GEMINI_API_KEY:dummy}
      model: ${GEMINI_MODEL:gemini-1.5-flash}
      base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1}

rate-limiting:
  monthly-limit: 100

app:
  chat:
    memory:
      max-messages: ${CHAT_MEMORY_MAX_MESSAGES:100}
      max-inactive-minutes: ${CHAT_MEMORY_MAX_INACTIVE_MINUTES:1440}

cache:
  enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ttl-seconds: 300

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://login.microsoftonline.com/common/v2.0
        audiences:
          - 6d8f19d3-001d-4047-b4e5-90b8dddda920