spring:
  application:
    name: hi-doc-api-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

ai:
  providers:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: ${OPENAI_MODEL:gpt-4o-mini}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    grok:
      api-key: ${GROK_API_KEY}
      model: ${GROK_MODEL:grok-2-mini}
      base-url: ${GROK_BASE_URL:https://api.x.ai/v1}
    gemini:
      api-key: ${GEMINI_API_KEY}
      model: ${GEMINI_MODEL:gemini-1.5-flash}
      base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1}

rate-limiting:
  monthly-limit: ${MONTHLY_LIMIT:100}

cache:
  enabled: ${CACHE_ENABLED:false}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ttl-seconds: ${CACHE_TTL_SECONDS:300}
